### ISSUE TITLE
Ошибка при сравнении баз NullPointerException

### ISSUE THREAD

**Issue by dimahetman** [pgcodekeeper/pgcodekeeper#126]
При сравнении 2 БД

1. PostgreSQL 14.9 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
2. PostgreSQL 14.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4), 64-bit

An internal error occurred during: "Загрузка схемы БД из agrocrmdb".
java.lang.NullPointerException

при этом эта схема agrocrmdb пустая в обоих БД
```
java.lang.reflect.InvocationTargetException
	at ru.taximaxim.codekeeper.ui.differ.TreeDiffer.finishJobs(TreeDiffer.java:138)
	at ru.taximaxim.codekeeper.ui.differ.TreeDiffer.run(TreeDiffer.java:95)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.lang.NullPointerException
	at ru.taximaxim.codekeeper.ui.differ.DbSource.getPgDiffArgs(DbSource.java:153)
	at ru.taximaxim.codekeeper.ui.differ.DbSource.getPgDiffArgs(DbSource.java:125)
	at ru.taximaxim.codekeeper.ui.differ.DbSourceJdbc.loadInternal(DbSource.java:466)
	at ru.taximaxim.codekeeper.ui.differ.DbSource.get(DbSource.java:96)
	at ru.taximaxim.codekeeper.ui.differ.TreeDiffer$DbSourceJob.run(TreeDiffer.java:157)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
	Suppressed: java.lang.NullPointerException
		... 6 more
Root exception:
java.lang.NullPointerException
	at ru.taximaxim.codekeeper.ui.differ.DbSource.getPgDiffArgs(DbSource.java:153)
	at ru.taximaxim.codekeeper.ui.differ.DbSource.getPgDiffArgs(DbSource.java:125)
	at ru.taximaxim.codekeeper.ui.differ.DbSourceJdbc.loadInternal(DbSource.java:466)
	at ru.taximaxim.codekeeper.ui.differ.DbSource.get(DbSource.java:96)
	at ru.taximaxim.codekeeper.ui.differ.TreeDiffer$DbSourceJob.run(TreeDiffer.java:157)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
	Suppressed: java.lang.NullPointerException
		... 6 more
```
pgCodeKeeper
Версия: 8.9.0, id сборки: 202311070824  
java.version=11.0.12

**Comment by AXEPOH** [comment]
Исправлено в 4afa43a27ad31d7872ccbb56283dc6cf302dd37c
