### ISSUE TITLE
Загрузка функций в PostgreSQL 11

### ISSUE THREAD

**Issue by sharkerr** [pgcodekeeper/pgcodekeeper#30]
При попытке инициализировать проект, происходит ошибка
![image](https://user-images.githubusercontent.com/5236188/47354048-5e5fb780-d6c6-11e8-93a8-c8a24f0ed22c.png)
java.lang.reflect.InvocationTargetException: IOException while creating project: Error while reading database schema via JDBC, error occured while processing jdbc:FunctionsReader query
ERROR: column p.proiswindow does not exist
  Position: 483
at ru.taximaxim.codekeeper.ui.pgdbproject.InitProjectFromSource.run(InitProjectFromSource.java:41)
at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.io.IOException: Error while reading database schema via JDBC, error occured while processing jdbc:FunctionsReader query
ERROR: column p.proiswindow does not exist
  Position: 483
at cz.startnet.utils.pgdiff.loader.JdbcLoader.getDbFromJdbc(JdbcLoader.java:130)
at cz.startnet.utils.pgdiff.loader.JdbcLoader.getDbFromJdbc(JdbcLoader.java:63)
at ru.taximaxim.codekeeper.ui.differ.DbSourceJdbc.loadInternal(DbSource.java:409)
at ru.taximaxim.codekeeper.ui.differ.DbSource.get(DbSource.java:71)
at ru.taximaxim.codekeeper.ui.pgdbproject.InitProjectFromSource.initRepoFromSource(InitProjectFromSource.java:55)
at ru.taximaxim.codekeeper.ui.pgdbproject.InitProjectFromSource.run(InitProjectFromSource.java:37)
... 1 more
Caused by: org.postgresql.util.PSQLException: ERROR: column p.proiswindow does not exist
  Position: 483
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:301)
at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:287)
at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:264)
at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:231)
at cz.startnet.utils.pgdiff.loader.jdbc.JdbcReader.read(JdbcReader.java:54)
at cz.startnet.utils.pgdiff.loader.JdbcLoader.getDbFromJdbc(JdbcLoader.java:102)
... 6 more

Eclipse - Version: 2018-09 (4.9.0)
Postgres 11.0
pgCodeKeeper 5.1.6

**Comment by Endeavourl** [comment]
В PostgreSQL 11 убрали колонку из метаданных pg_proc. Исправим.

**Comment by Endeavourl** [comment]
исправлено в fe408493d7d00cc3b4ee59ba83f09f2227ce9cc5
