### ISSUE TITLE
WITH inside WITH crashes pgcodekeeper

### ISSUE THREAD

**Issue by iupton** [pgcodekeeper/pgcodekeeper#54]
This view cannot be parsed using pgCodeKeeper v5.5.3 (neither GUI nor CLI):

```
CREATE OR REPLACE VIEW public.test1 as
with ind as (
	select * from pg_index i cross join unnest(i.indkey) with ordinality c (colnum, ordinality)
)
select * from ind;
```

I receive this stack trace: 

```
java.io.IOException: Error while reading database schema via JDBC, error occured while processing jdbc:/public/test1
null
	at cz.startnet.utils.pgdiff.loader.JdbcLoader.getDbFromJdbc(JdbcLoader.java:117)
	at cz.startnet.utils.pgdiff.loader.JdbcLoader.getDbFromJdbc(JdbcLoader.java:53)
	at cz.startnet.utils.pgdiff.PgDiff.loadDatabaseSchema(PgDiff.java:140)
	at cz.startnet.utils.pgdiff.PgDiff.createDiff(PgDiff.java:62)
	at ru.taximaxim.codekeeper.cli.Main.diff(Main.java:80)
	at ru.taximaxim.codekeeper.cli.Main.main(Main.java:57)
	at ru.taximaxim.codekeeper.cli.ApplicationStandalone.start(ApplicationStandalone.java:16)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
Caused by: java.lang.NullPointerException
	at cz.startnet.utils.pgdiff.parsers.antlr.rulectx.SelectStmt.withClause(SelectStmt.java:34)
	at cz.startnet.utils.pgdiff.parsers.antlr.expr.ViewSelect.analyze(ViewSelect.java:109)
	at cz.startnet.utils.pgdiff.loader.jdbc.ViewsReader.lambda$1(ViewsReader.java:63)
	at cz.startnet.utils.pgdiff.loader.jdbc.JdbcLoaderBase.lambda$1(JdbcLoaderBase.java:487)
	at cz.startnet.utils.pgdiff.parsers.antlr.AntlrTask.finish(AntlrTask.java:25)
	at cz.startnet.utils.pgdiff.parsers.antlr.AntlrParser.finishAntlr(AntlrParser.java:192)
	at cz.startnet.utils.pgdiff.loader.jdbc.JdbcLoaderBase.finishAntlr(JdbcLoaderBase.java:493)
	at cz.startnet.utils.pgdiff.loader.JdbcLoader.getDbFromJdbc(JdbcLoader.java:107)
	... 19 more
```

It seems the ANTLR parser does not like WITH keyword inside a WITH subquery. The following version of the view will parse with no errors:

```
create or replace view public.test1 as
select * from pg_index i cross join unnest(i.indkey) with ordinality c (colnum, ordinality)
```

**Comment by AXEPOH** [comment]
Syntax "WITH ORDINALITY" was not supported.
Second version was also broken ...

fixed in https://github.com/pgcodekeeper/pgcodekeeper/commit/d9e10cbe8ec246068ef5a33e60c8a8307fac7880
